Development
Kaneez98Fatima/portfolio_website pull request #1
Opened 2021-06-06 07:26 UTC by Kaneez98Fatima

The 2 sections I build for this project are:

The toolbar (or header):
The headline section (right after the header):

2021-06-09 17:13 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @Kaneez98Fatima , 

Your project looks amazing. You well used flex to align your elements :+1: 
Good job so far!

There are some issues that you still need to work on to go further but you are almost there!


 ## Required Changes ♻️
_Please check the inline comments for my suggestions_ :arrow_down:


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-09 17:13 UTC, sinansevgi commented on portfolio_website.html
> +      </h1>
- [ ] Instead of using span, you should use a different header tag hx for "I'am a Software Developer" part.

2021-06-09 17:13 UTC, sinansevgi commented on portfolio_website.html
> +        </div>
- [ ] You should use list tags (ul/li) to semantically group your social icons.

2021-06-10 00:21 UTC, MahmoudBakr23 approved these changes
Hi @Kaneez98Fatima  😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Optional**
Next time, please don't forget about the PR headline and write a short descriptive headline about it.
It helps to keep it professional and understandable of what exactly it's about. 
> I'm sorry this didn't show up for you in the earlier review. 

_Also, see the **Optional** comments down below._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-10 00:21 UTC, MahmoudBakr23 commented on README.md
> +https://kaneez98fatima.github.io/portfolio_website/
**Optional**
It's so important to write a professional Readme file for your projects.
You can always refer to this [template](https://github.com/microverseinc/readme-template) to do so.

2021-06-10 00:21 UTC, MahmoudBakr23 commented on portfolio_website.html
> +
**Optional**
Please keep in mind that adding blank links is only for a good reason such as separating two logical pieces of code or two large sections apart.

2021-06-10 00:21 UTC, MahmoudBakr23 commented on styles.css
> +h1 {
**Optional**
Kindly keep in mind that following the given design is so important for you in best practices and also for making the website professional, consistent, and good looking.
You should follow the design template in typography, font size, font weight, colors, images, and spacings (margin and padding) 
_Take a look at the images down below._
> I'm sorry this didn't show up for you in the earlier review.
### **Your design**
![Screenshot_2021-06-10-02-07-13-26](https://user-images.githubusercontent.com/47625407/121445043-f6eaf900-c990-11eb-9ed5-23446d6f9dab.jpg)
### **[Original design](https://www.figma.com/file/NWVDbyHlxMtZO5VX92hpM1/Microverse-Student-Project-1-Copy?fuid=892210429043439399)**
![Screenshot_2021-06-10-02-06-57-10](https://user-images.githubusercontent.com/47625407/121445066-02d6bb00-c991-11eb-96e8-e3bc63eab0c7.jpg)

2021-06-10 03:33 UTC, merged